### PR TITLE
Fix for tvshow poster/fanart(Seren) & some other quick fix

### PR DESCRIPTION
**Pull request by vitorp07**

### CODE REVIEW

**Comment by SerpentDrago** [comment]
I could seriously hug you right now , THANKS a ton . 

... if you get bored feel free to make any other PR's :)

**Comment by SerpentDrago** [comment]
Would you like to help out , Join our Metallliq / EIM   Project  ?  

Anything you could help out with would be nice .  I'm not a coder per say but very technical and can copy and paste .  DR knows much more . we also have a updated Aftermath wizard . 


Do you have telegram ?

**Comment by vitorp07** [comment]
My pleasure... I would be glad to help out where needed, I'm not the best developer out there but it happens that Meta and EIM is the plugins I know the most(learned a lot from Q and Mid).
Do not have telegram account(do have a reddit) but I could get one if it's easier that way.

**Comment by SerpentDrago** [comment]
You have widgets working ? #9 

https://t.me/joinchat/CJYMGxKjZpS5VL4_NI8jvw

telegram invite , when you join i'll delete that invite link

**Pull request merged**
